"""empty message

Revision ID: 43c374eb00d4
Revises: 974aedc647ec
Create Date: 2021-12-10 12:45:56.493532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43c374eb00d4'
down_revision = '974aedc647ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('create_date', sa.DateTime(), nullable=False))
    op.drop_column('question', 'create_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('create_time', sa.DATETIME(), nullable=False))
    op.drop_column('question', 'create_date')
    # ### end Alembic commands ###
